DROP TABLE IF EXISTS `t_p_notice`;
CREATE TABLE `t_p_notice` (
  `noticeId` int(11) NOT NULL AUTO_INCREMENT COMMENT '公告id',
  `title` varchar(32) DEFAULT NULL COMMENT '标题（今日重点播报、优惠活动、订单消息、）',
  `content` text COMMENT '内容',
  `type` tinyint(4) DEFAULT NULL COMMENT '公告类别（0-今日重点播报、1-优惠活动、2-订单消息 3-喱喱头条、4-我的消息）',
  `time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '创建时间',
  `adminId` int(11) DEFAULT NULL COMMENT '公告创建者id',
  `userType` tinyint(4) DEFAULT '0' COMMENT '通知对象 (0 全体用户 1 全体教练 2 全体学员 1指定教练 2 指定学员 3驾校教练 4驾校学员 5 城市教练 6城市学员 7特约教练 8普通教练 9-cms消息中心配置教练消息 10-cms消息中心配置学员消息)',
  `userId` bigint(11) DEFAULT NULL COMMENT '用户id 当通知类型为0时为空',
  `extra` varchar(254) DEFAULT NULL,
  `isdel` tinyint(4) DEFAULT '0' COMMENT '状态：0-已发布；1-已删除 2-草稿',
  `etime` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '截止时间，过了截止时间的消息不再展示',
  `pic` varchar(100) DEFAULT NULL COMMENT '消息的图片',
  `clickNum` int(11) DEFAULT '0' COMMENT '点击量',
  `applyexam` varchar(1000) DEFAULT NULL COMMENT '学员进度，根据学员表的applyexam和applystate两字段组合',
  `cityId` varchar(200) DEFAULT NULL COMMENT '城市Id',
  `schoolId` varchar(500) DEFAULT NULL COMMENT '驾校Id',
  `schoolName` varchar(500) DEFAULT NULL COMMENT '驾校名称',
  `userName` varchar(1000) DEFAULT NULL COMMENT '学员名称',
  `utype` varchar(200) DEFAULT NULL COMMENT '通知类型（1-驾校学员 2-喱喱学员 3-特约教练 4-普通教练）',
  `userIdStrs` varchar(1000) DEFAULT NULL COMMENT '学员名称用逗号隔开',
  `digest` varchar(200) DEFAULT NULL COMMENT '摘要',
  `orderId` varchar(32) DEFAULT NULL COMMENT '订单Id',
  `msgType` int(11) DEFAULT '0' COMMENT '消息推送ID，与JpushConstant类定义一致',
  PRIMARY KEY (`noticeId`),
  KEY `INDEX_USERID` (`userId`),
  KEY `INDEX_TYPE` (`type`),
  KEY `INDEX_USERTYPE` (`userType`)
) ENGINE=InnoDB AUTO_INCREMENT=38560 DEFAULT CHARSET=utf8 COMMENT='系统消息通知';
