
-- ctime 新建时设置默认值
ALTER TABLE t_complain MODIFY ctime  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;
-- mtime 更新时默认值
ALTER TABLE t_complain MODIFY mtime  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;


-- ctime 新建时设置默认值
ALTER TABLE t_complain_return MODIFY ctime  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;
-- mtime 更新时默认值
ALTER TABLE t_complain_return MODIFY mtime  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP ; 